export interface BlogPostMeta {
  slug: string
  title: string
  description: string
  date: string
  readTime: string
  keywords: string[]
  related?: string[]
}

export const BLOG_POSTS: BlogPostMeta[] = [
  {
    slug: 'executive-search-timing-signals',
    title: 'Executive Search Timing Signals: What Appears Before a Role Is Posted',
    description: 'The strongest executive opportunities are often visible through weak signals before a formal posting appears. Here is what to watch and how to act without overreacting to noise.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive search timing signals',
      'early role signals',
      'pre-posting executive opportunities',
      'executive hiring signal detection',
      'executive transition timing',
    ],
    related: ['how-we-estimate-early-role-signals', 'target-company-list', 'cio-job-market-2026'],
  },
  {
    slug: 'executive-coaching-search-outcomes',
    title: 'Does Executive Coaching Improve Search Outcomes? What The Evidence Shows',
    description: 'Executive coaching can improve outcomes when it is paired with clear operating cadence, explicit commitments, and role-specific preparation. This is what the evidence supports and where it does not.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive coaching effectiveness job search',
      'executive coaching outcomes',
      'coaching and executive transitions',
      'executive search coaching evidence',
      'leadership coaching job search',
    ],
    related: ['executive-coaching-job-search', 'executive-coaching-candidate-infrastructure', 'pilot-findings'],
  },
  {
    slug: 'executive-transition-success-factors',
    title: 'Executive Transition Success Factors: What Predicts Better Outcomes',
    description: 'Transition success is shaped by preparation depth, signal timing, and execution consistency. Here are the factors that matter most in the first 90 days of a search campaign.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'executive transition success factors',
      'executive onboarding and transition',
      'c-suite transition outcomes',
      'executive search success drivers',
      'senior leadership transition strategy',
    ],
    related: ['vp-to-cio-transition', 'executive-search-operating-system', 'pilot-findings'],
  },
  {
    slug: 'executive-search-consistency-model',
    title: 'Behavior Change For Senior Candidates: Why Consistency Beats Intensity',
    description: 'Most executive campaigns stall from drift, not effort. Consistent weekly execution beats short bursts of high activity when the search timeline is long and uncertain.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive job search consistency',
      'executive search behavior change',
      'c-suite search cadence',
      'executive campaign discipline',
      'executive search weekly model',
    ],
    related: ['executive-job-search-daily-routine', 'executive-search-operating-system', 'pilot-findings'],
  },
  {
    slug: 'executive-hiring-patterns-2026',
    title: 'We Analyzed 300+ Executive Hiring Profiles. Here Is What Actually Gets Senior Leaders Interviewed.',
    description: 'Most executive candidates still position around tenure and title. Hiring teams at the C-suite and VP level screen for transformation evidence, cross-functional influence, and business outcomes. Here is what the data says.',
    date: '2026-05-15',
    readTime: '6 min read',
    keywords: [
      'executive hiring trends 2026',
      'C-suite hiring patterns',
      'VP hiring criteria',
      'executive positioning strategy',
      'what gets executives interviewed',
      'senior leadership recruiting signals',
      'executive job search data',
    ],
    related: ['executive-resume-gaps', 'linkedin-executive-search-strategy', 'executive-job-search-daily-routine'],
  },
  {
    slug: 'why-executive-recruiters-go-quiet',
    title: 'Why Executive Recruiters Go Quiet (And How Senior Candidates Can Break the Pattern)',
    description: 'Strong candidates are often ignored for reasons that have little to do with capability and everything to do with decision pressure. The frame you use in outreach can reduce that pressure and increase response rates.',
    date: '2026-05-15',
    readTime: '6 min read',
    keywords: [
      'executive recruiter ghosting',
      'executive outreach response rate',
      'C-suite candidate messaging',
      'VP candidate outreach strategy',
      'how to message executive recruiters',
      'senior candidate outreach framework',
      'executive search communication',
    ],
    related: ['retained-search-firms', 'executive-search-firms-cio', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'why-starting-monday-exists',
    title: 'Why Starting Monday Exists: Executive Search Is Not a Resume Problem',
    description: 'C-suite and VP searches are won on specificity, timing, and preparation quality. We built Starting Monday to replace generic templates with role-specific positioning and high-context execution.',
    date: '2026-05-15',
    readTime: '5 min read',
    keywords: [
      'why starting monday exists',
      'executive search operating system',
      'C-suite search strategy',
      'VP executive transition',
      'executive positioning infrastructure',
      'senior leadership career transition',
      'how to run executive job search',
    ],
    related: ['executive-search-operating-system', 'target-company-list', 'executive-job-search-daily-routine'],
  },
  {
    slug: 'how-we-estimate-early-role-signals',
    title: 'How We Estimate Early Role Signals (And Why We Use a 1-3 Week Window)',
    description: 'A transparent look at our methodology: how we define event dates, posting dates, lag windows, and the primary sources we use to estimate early executive-role timing signals.',
    date: '2026-05-13',
    readTime: '6 min read',
    keywords: [
      'executive role timing methodology',
      'how we estimate job posting lead time',
      '8-K hiring signals',
      'career page monitoring method',
      'executive search timing signals',
      'decision to posting lag',
      'C-suite hiring signal model',
    ],
    related: ['cio-job-market-2026', 'target-company-list', 'executive-search-firms-cio'],
  },
  {
    slug: 'executive-job-search-daily-routine',
    title: 'Executive Job Search Daily Routine: What the Top 1% Do Differently',
    description: 'The strongest executive candidates run a disciplined daily operating rhythm: signals, targeted outreach, prep, and follow-through. Here is the exact routine and the weekly metrics that keep momentum high.',
    date: '2026-05-12',
    readTime: '6 min read',
    keywords: [
      'executive job search daily routine',
      'daily executive search workflow',
      'CIO job search habits',
      'executive search discipline',
      'how top executive candidates run search',
      'executive outreach routine',
      'senior candidate job search strategy',
      'executive search operating cadence',
    ],
    related: ['executive-search-operating-system', 'how-cios-find-jobs', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'executive-search-firms-cio',
    title: 'What Executive Search Firms Actually Want from C-suite Candidates',
    description: 'Most technology executives think about executive search firms the wrong way. Here is how retained search actually works, what gets you on the short list, and why timing matters more than almost anything else.',
    date: '2026-05-06',
    readTime: '6 min read',
    keywords: [
      'executive search firms C-suite',
      'how to work with executive search firms',
      'C-suite search firms',
      'what executive recruiters want',
      'C-suite job search strategy',
      'retained executive search',
      'how to get on C-suite short list',
    ],
    related: ['retained-search-firms', 'how-cios-find-jobs', 'cio-job-search-timeline'],
  },
  {
    slug: 'cio-job-search-timeline',
    title: 'How Long Does a C-suite Job Search Really Take?',
    description: 'The honest answer most people do not say out loud: six to eighteen months. The range is that wide for a reason, and where you land in it depends on decisions you make before you start.',
    date: '2026-05-06',
    readTime: '5 min read',
    keywords: [
      'C-suite job search timeline',
      'how long does executive job search take',
      'C-suite job search strategy',
      'executive job search timeline',
      'technology executive search',
      'C-suite career transition',
    ],
    related: ['target-company-list', 'executive-search-firms-cio', 'how-cios-find-jobs'],
  },
  {
    slug: 'vp-to-cio-transition',
    title: 'How VPs of Technology Make the Move to the C-suite',
    description: 'The VP-to-CIO move is not a promotion. It is a repositioning. What changes in the CIO seat, what search firms look for, and how to build the case before the search starts.',
    date: '2026-05-07',
    readTime: '5 min read',
    keywords: [
      'VP to C-suite transition',
      'VP technology to C-suite',
      'how to become C-suite',
      'VP IT to C-suite',
      'C-suite career path',
      'technology executive promotion',
      'VP of technology career',
    ],
    related: ['cio-vs-cto-which-role', 'executive-resume-gaps', 'cio-job-search-timeline'],
  },
  {
    slug: 'cio-job-market-2026',
    title: 'We Scanned 600+ Career Pages in Q2 2026. Here Is What C-suite Hiring Looks Like Right Now.',
    description: 'Real data from monitoring hundreds of company career pages across technology-intensive sectors. What the C-suite job market looks like in Q2 2026, which signals precede a search, and how to monitor career pages before roles appear on LinkedIn.',
    date: '2026-05-10',
    readTime: '7 min read',
    keywords: [
      'C-suite job market 2026',
      'C-suite hiring trends 2026',
      'how to monitor company career pages',
      'executive job market Q2 2026',
      'C-suite job search 2026',
      'technology executive hiring',
      'career page monitoring',
      'C-suite opportunities 2026',
    ],
    related: ['cio-job-search-timeline', 'executive-search-firms-cio', 'target-company-list'],
  },
  {
    slug: 'ciso-interview-preparation',
    title: 'How to Prepare for a CISO Interview',
    description: 'CISO interviews test something most security executives are not trained to do: explain risk in business terms to a room that does not think in frameworks. Here is how to prepare for the conversations that actually matter.',
    date: '2026-05-07',
    readTime: '5 min read',
    keywords: [
      'CISO interview preparation',
      'CISO interview questions',
      'chief information security officer interview',
      'how to prepare for CISO interview',
      'cybersecurity executive interview',
      'CISO board presentation',
    ],
    related: ['what-companies-want-chief-data-officer', 'executive-resume-gaps', 'executive-search-operating-system'],
  },
  {
    slug: 'what-companies-want-chief-data-officer',
    title: 'What Companies Actually Want in a Chief Data Officer',
    description: 'Most CDO job descriptions tell you what the company wants you to do. Very few tell you what they actually need. The gap between those two things is where most CDO searches go wrong.',
    date: '2026-05-07',
    readTime: '5 min read',
    keywords: [
      'chief data officer requirements',
      'what companies look for in CDO',
      'chief data officer skills',
      'CDO hiring criteria',
      'chief data officer job search',
      'chief data officer career',
    ],
    related: ['ciso-interview-preparation', 'executive-resume-gaps', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'cio-compensation-negotiation',
    title: 'How to Negotiate C-suite Compensation',
    description: 'The compensation conversation for a C-suite role has a different structure than every negotiation you have had before. What to know before the offer, how to read the room, and where most executives leave money on the table.',
    date: '2026-05-07',
    readTime: '6 min read',
    keywords: [
      'C-suite compensation',
      'C-suite salary negotiation',
      'chief information officer compensation',
      'how to negotiate executive compensation',
      'C-suite total compensation',
      'technology executive salary',
      'C-suite offer negotiation',
    ],
    related: ['pe-backed-cio', 'retained-search-firms', 'cio-job-search-timeline'],
  },
  {
    slug: 'cio-board-presentation',
    title: 'How to Prepare for a Board Presentation as a New C-suite Executive',
    description: 'The board presentation is not a technology briefing. It is a risk and value conversation. What the board actually wants to hear in the first ninety days, and how to walk in ready.',
    date: '2026-05-08',
    readTime: '5 min read',
    keywords: [
      'C-suite board presentation',
      'new C-suite board meeting',
      'C-suite presenting to board of directors',
      'technology board presentation',
      'C-suite first 90 days',
      'how to present to board as C-suite',
      'C-suite board communication',
    ],
    related: ['vp-to-cio-transition', 'pe-backed-cio', 'cio-compensation-negotiation'],
  },
  {
    slug: 'pe-backed-cio',
    title: 'What PE-Backed Companies Look for in a C-suite Technology Leader',
    description: 'PE-backed companies hire C-suite leaders for a different reason than public companies do. The mandate is tighter, the timeline is compressed, and the equity is structured around an exit. What you need to know before you take the call.',
    date: '2026-05-08',
    readTime: '6 min read',
    keywords: [
      'PE-backed C-suite',
      'private equity C-suite',
      'C-suite private equity company',
      'technology leader private equity',
      'C-suite equity compensation PE',
      'private equity technology executive',
      'C-suite portfolio company',
    ],
    related: ['cio-board-presentation', 'cio-compensation-negotiation', 'executive-search-firms-cio'],
  },
  {
    slug: 'executive-resume-gaps',
    title: 'The Executive Resume Gaps That Kill C-suite Candidacies',
    description: 'Most executive resumes are read by a search firm associate before they reach a partner. Here are the gaps that filter candidates out before the first conversation and how to close them.',
    date: '2026-05-08',
    readTime: '5 min read',
    keywords: [
      'C-suite resume',
      'executive resume for C-suite',
      'C-suite resume tips',
      'technology executive resume',
      'how to write a C-suite resume',
      'C-suite resume mistakes',
      'executive resume gaps',
    ],
    related: ['linkedin-executive-search-strategy', 'retained-search-firms', 'vp-to-cio-transition'],
  },
  {
    slug: 'retained-search-firms',
    title: 'How to Work with Retained Search Firms Without Losing Leverage',
    description: 'Retained search firms work for the client, not the candidate. Understanding how they actually operate changes how you manage every relationship and every search.',
    date: '2026-05-08',
    readTime: '5 min read',
    keywords: [
      'retained search firms CIO',
      'how to work with executive recruiters',
      'executive search firm strategy',
      'CIO headhunter relationship',
      'retained search candidate strategy',
      'executive recruiter tips',
      'how to get on CIO short list',
    ],
    related: ['executive-search-firms-cio', 'how-cios-find-jobs', 'target-company-list'],
  },
  {
    slug: 'target-company-list',
    title: 'How to Build Your Target Company List for an Executive Search',
    description: 'The fastest C-suite searches start with a list. Not of job openings. Those are late. A list of forty to sixty companies you would say yes to before the offer is made. Here is how to build it, what to put on it, and what to watch for once you have it.',
    date: '2026-05-10',
    readTime: '6 min read',
    keywords: [
      'executive job search target company list',
      'C-suite job search strategy',
      'how to find executive jobs before they post',
      'target company list executive search',
      'C-suite search campaign',
      'executive search strategy',
      'technology executive job search',
      'how to build executive job search list',
    ],
    related: ['executive-search-operating-system', 'retained-search-firms', 'cio-job-search-timeline'],
  },
  {
    slug: 'cio-vs-cto-which-role',
    title: 'CIO vs CTO: Which Role Is Right for You?',
    description: 'Most technology executives spend their career in one seat without seriously considering whether the other fits better. The CIO drawn to product strategy might be a natural CTO. The CTO frustrated by ambiguity might be a natural CIO. Here is how to tell.',
    date: '2026-05-11',
    readTime: '5 min read',
    keywords: [
      'CIO vs CTO',
      'CIO or CTO which is right for me',
      'difference between CIO and CTO',
      'CIO vs CTO career path',
      'should I be a CIO or CTO',
      'technology executive career decision',
      'CIO CTO difference',
      'chief information officer vs chief technology officer',
    ],
    related: ['cto-vs-vp-engineering-career-path', 'vp-to-cio-transition', 'cto-job-search-timeline'],
  },
  {
    slug: 'cto-vs-vp-engineering-career-path',
    title: 'CTO vs VP of Engineering: Which Path Is Right for Your Next Move?',
    description: 'Most technology executives reach for the title with more letters. That is the wrong frame. The real question is which role matches how you create value and what kind of work makes you excellent.',
    date: '2026-05-11',
    readTime: '6 min read',
    keywords: [
      'CTO vs VP Engineering',
      'VP engineering vs CTO career path',
      'should I be CTO or VP Engineering',
      'CTO career path',
      'VP of engineering career',
      'technology executive title decision',
      'CTO vs VP engineering difference',
      'chief technology officer vs VP engineering',
    ],
    related: ['cio-vs-cto-which-role', 'cto-job-search-timeline', 'target-company-list-cto'],
  },
  {
    slug: 'cto-job-search-timeline',
    title: 'How Long Does a CTO Job Search Really Take?',
    description: 'Ask companies how long a CTO search takes and they will say 8 to 12 weeks. Ask candidates and the honest answer is very different. What determines where you fall in the range and what you can actually control.',
    date: '2026-05-11',
    readTime: '5 min read',
    keywords: [
      'how long does CTO job search take',
      'CTO job search timeline',
      'chief technology officer job search time',
      'CTO career transition timeline',
      'how long to find CTO job',
      'technology executive job search timeline',
      'CTO executive search duration',
    ],
    related: ['target-company-list-cto', 'cto-vs-vp-engineering-career-path', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'linkedin-executive-search-strategy',
    title: 'How to Use LinkedIn in an Active CIO or CTO Search',
    description: 'LinkedIn is the only professional platform where your most important future employers spend time. Used well, it builds inbound interest without looking like you are searching. Used poorly, it is a credibility liability. Here is the difference.',
    date: '2026-05-12',
    readTime: '6 min read',
    keywords: [
      'LinkedIn executive job search',
      'CIO LinkedIn strategy',
      'CTO LinkedIn job search',
      'how to use LinkedIn for executive search',
      'executive LinkedIn profile tips',
      'CIO CTO LinkedIn active search',
      'technology executive LinkedIn strategy',
    ],
    related: ['executive-resume-gaps', 'executive-search-operating-system', 'how-cios-find-jobs'],
  },
  {
    slug: 'how-cios-find-jobs',
    title: 'How Do CIOs Actually Find New Jobs?',
    description: 'Not job boards. Not LinkedIn Easy Apply. Not cold-emailing recruiters. Here is how CIO roles are actually filled and what that means for how to run your search.',
    date: '2026-05-12',
    readTime: '5 min read',
    keywords: [
      'how do CIOs find jobs',
      'CIO job search strategy',
      'how CIOs get hired',
      'CIO hidden job market',
      'how to find CIO job',
      'CIO job search networking',
      'chief information officer job search',
      'how executive CIO jobs are filled',
    ],
    related: ['target-company-list', 'retained-search-firms', 'executive-search-operating-system'],
  },
  {
    slug: 'target-company-list-cto',
    title: 'How to Build Your Target Company List for a CTO Search',
    description: 'The CTO role has no agreed-upon definition. Before you can build a target company list, you have to decide which version of the CTO you are building toward. That decision shapes every other part of the search.',
    date: '2026-05-10',
    readTime: '7 min read',
    keywords: [
      'CTO job search strategy',
      'how to find CTO jobs',
      'target company list CTO search',
      'chief technology officer job search',
      'CTO executive search',
      'technology executive job search',
      'CTO career transition',
      'how to become CTO',
    ],
    related: ['cto-job-search-timeline', 'target-company-list', 'cto-vs-vp-engineering-career-path'],
  },
  {
    slug: 'executive-search-operating-system',
    title: 'The Search Has No Manager. Here Is How to Build One.',
    description: 'On the day your CIO role ends, you become your own organization: a one-person company with no revenue, no runway, and no manager. Most executives are not prepared for this. Here is what changes when you treat the search like a business.',
    date: '2026-05-10',
    readTime: '7 min read',
    keywords: [
      'executive career transition',
      'CIO job search system',
      'executive search operating system',
      'CIO career transition strategy',
      'technology executive career transition',
      'executive job search structure',
      'how to manage executive job search',
      'executive search campaign strategy',
    ],
    related: ['target-company-list', 'linkedin-executive-search-strategy', 'executive-coaching-job-search'],
  },
  {
    slug: 'executive-coaching-job-search',
    title: "What Executive Coaches Get Wrong About Their Clients' Job Searches",
    description: 'Most executive coaches underestimate how much of the search happens outside the session. Here is what changes when your clients have the right infrastructure.',
    date: '2026-05-10',
    readTime: '6 min read',
    keywords: [
      'executive coaching job search',
      'executive coach career transition',
      'how executive coaches help job search',
      'executive coaching tools',
      'executive job search support',
      'career coaching executives',
      'executive transition coaching',
      'tools for executive coaches',
    ],
    related: ['executive-search-operating-system', 'target-company-list', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'executive-coaching-candidate-infrastructure',
    title: 'The Infrastructure Gap in Executive Career Coaching',
    description: 'Most executive coaching practices are strong on strategy and weak on infrastructure. The gap shows up in first-round interviews, stalled pipelines, and sessions that spend too much time on context. Here is what changes when you fix it.',
    date: '2026-05-11',
    readTime: '6 min read',
    keywords: [
      'executive coaching job search tools',
      'tools for executive coaches',
      'executive career coaching infrastructure',
      'how executive coaches improve client search',
      'executive job search coaching',
      'executive coaching practice tools',
      'executive transition coaching tools',
      'executive coaching pipeline visibility',
    ],
    related: ['executive-coaching-job-search', 'coaches-guide', 'executive-search-operating-system'],
  },
  {
    slug: 'vp-job-search-different-rules',
    title: 'The Job Search Changes When You Reach VP. Here Is How.',
    description: 'Most of what you know about running a job search stops working at the senior executive level. The rules are different, the timeline is longer, and the preparation standard is higher. Here is what actually changes.',
    date: '2026-05-11',
    readTime: '6 min read',
    keywords: [
      'VP job search strategy',
      'executive job search different',
      'how job search changes at VP level',
      'senior executive job search rules',
      'VP CIO CTO job search',
      'executive career transition strategy',
      'job search VP and above',
      'how to find a VP job',
    ],
    related: ['how-cios-find-jobs', 'executive-search-firms-cio', 'target-company-list'],
  },
  {
    slug: 'technology-executive-transition-chro',
    title: 'What CHROs Should Know About Technology Executive Career Transition',
    description: 'Technology executive searches run longer and require different support than general executive outplacement. What CHROs can do to improve outcomes for CIOs, CTOs, and VPs of Technology in transition.',
    date: '2026-05-11',
    readTime: '6 min read',
    keywords: [
      'technology executive outplacement',
      'CHRO technology executive transition',
      'CIO career transition support',
      'chief information officer outplacement',
      'how to support technology executives in transition',
      'CHRO executive outplacement strategy',
      'technology executive career support',
    ],
    related: ['executive-coaching-candidate-infrastructure', 'retained-search-candidate-preparation', 'executive-search-operating-system'],
  },
  {
    slug: 'retained-search-candidate-preparation',
    title: 'Why Technology Executive Candidates Fail the First Round',
    description: 'The most common reason a technology executive candidate does not advance past the first round is not fit. It is preparation. What adequate preparation looks like at the senior level, and what search firms can do about the gap.',
    date: '2026-05-11',
    readTime: '5 min read',
    keywords: [
      'technology executive candidate preparation',
      'why CIO candidates fail interviews',
      'executive candidate first round interview',
      'retained search candidate preparation',
      'technology executive interview preparation',
      'executive search candidate tools',
      'CIO interview preparation for search firms',
      'how to prepare executive candidates for interviews',
    ],
    related: ['executive-search-firms-cio', 'retained-search-firms', 'executive-search-operating-system'],
  },
]

export function getPost(slug: string): BlogPostMeta | undefined {
  return BLOG_POSTS.find(p => p.slug === slug)
}

export function getRelated(slug: string): BlogPostMeta[] {
  const post = getPost(slug)
  if (!post?.related) return []
  return post.related.map(s => getPost(s)).filter(Boolean) as BlogPostMeta[]
}
