export interface BlogPostMeta {
  slug: string
  title: string
  description: string
  date: string
  readTime: string
  keywords: string[]
}

export const BLOG_POSTS: BlogPostMeta[] = [
  {
    slug: 'executive-search-firms-cio',
    title: 'What Executive Search Firms Actually Want from CIO Candidates',
    description: 'Most technology executives think about executive search firms the wrong way. Here is how retained search actually works, what gets you on the short list, and why timing matters more than almost anything else.',
    date: '2026-05-06',
    readTime: '6 min read',
    keywords: [
      'executive search firms CIO',
      'how to work with executive search firms',
      'CIO search firms',
      'what executive recruiters want',
      'CIO job search strategy',
      'retained executive search',
      'how to get on CIO short list',
    ],
  },
  {
    slug: 'cio-job-search-timeline',
    title: 'How Long Does a CIO Job Search Really Take?',
    description: 'The honest answer most people do not say out loud: six to eighteen months. The range is that wide for a reason, and where you land in it depends on decisions you make before you start.',
    date: '2026-05-06',
    readTime: '5 min read',
    keywords: [
      'CIO job search timeline',
      'how long does executive job search take',
      'CIO job search strategy',
      'executive job search timeline',
      'technology executive search',
      'CIO career transition',
    ],
  },
  {
    slug: 'vp-to-cio-transition',
    title: 'How VPs of Technology Make the Move to CIO',
    description: 'The VP-to-CIO move is not a promotion. It is a repositioning. What changes in the CIO seat, what search firms look for, and how to build the case before the search starts.',
    date: '2026-05-07',
    readTime: '5 min read',
    keywords: [
      'VP to CIO transition',
      'VP technology to CIO',
      'how to become a CIO',
      'VP IT to CIO',
      'CIO career path',
      'technology executive promotion',
      'VP of technology career',
    ],
  },
  {
    slug: 'ciso-interview-preparation',
    title: 'How to Prepare for a CISO Interview',
    description: 'CISO interviews test something most security executives are not trained to do: explain risk in business terms to a room that does not think in frameworks. Here is how to prepare for the conversations that actually matter.',
    date: '2026-05-07',
    readTime: '5 min read',
    keywords: [
      'CISO interview preparation',
      'CISO interview questions',
      'chief information security officer interview',
      'how to prepare for CISO interview',
      'cybersecurity executive interview',
      'CISO board presentation',
    ],
  },
  {
    slug: 'what-companies-want-chief-data-officer',
    title: 'What Companies Actually Want in a Chief Data Officer',
    description: 'Most CDO job descriptions tell you what the company wants you to do. Very few tell you what they actually need. The gap between those two things is where most CDO searches go wrong.',
    date: '2026-05-07',
    readTime: '5 min read',
    keywords: [
      'chief data officer requirements',
      'what companies look for in CDO',
      'chief data officer skills',
      'CDO hiring criteria',
      'chief data officer job search',
      'chief data officer career',
    ],
  },
  {
    slug: 'cio-compensation-negotiation',
    title: 'How to Negotiate CIO Compensation',
    description: 'The compensation conversation for a CIO role has a different structure than every negotiation you have had before. What to know before the offer, how to read the room, and where most executives leave money on the table.',
    date: '2026-05-07',
    readTime: '6 min read',
    keywords: [
      'CIO compensation',
      'CIO salary negotiation',
      'chief information officer compensation',
      'how to negotiate executive compensation',
      'CIO total compensation',
      'technology executive salary',
      'CIO offer negotiation',
    ],
  },
  {
    slug: 'cio-board-presentation',
    title: 'How to Prepare for a Board Presentation as a New CIO',
    description: 'The board presentation is not a technology briefing. It is a risk and value conversation. What the board actually wants to hear in the first ninety days, and how to walk in ready.',
    date: '2026-05-08',
    readTime: '5 min read',
    keywords: [
      'CIO board presentation',
      'new CIO board meeting',
      'CIO presenting to board of directors',
      'technology board presentation',
      'CIO first 90 days',
      'how to present to board as CIO',
      'CIO board communication',
    ],
  },
  {
    slug: 'pe-backed-cio',
    title: 'What PE-Backed Companies Look for in a CIO',
    description: 'PE-backed companies hire CIOs for a different reason than public companies do. The mandate is tighter, the timeline is compressed, and the equity is structured around an exit. What you need to know before you take the call.',
    date: '2026-05-08',
    readTime: '6 min read',
    keywords: [
      'PE-backed CIO',
      'private equity CIO',
      'CIO private equity company',
      'technology leader private equity',
      'CIO equity compensation PE',
      'private equity technology executive',
      'CIO portfolio company',
    ],
  },
  {
    slug: 'executive-resume-gaps',
    title: 'The Executive Resume Gaps That Kill CIO Candidacies',
    description: 'Most CIO resumes are read by a search firm associate before they reach a partner. Here are the gaps that filter candidates out before the first conversation and how to close them.',
    date: '2026-05-08',
    readTime: '5 min read',
    keywords: [
      'CIO resume',
      'executive resume for CIO',
      'CIO resume tips',
      'technology executive resume',
      'how to write a CIO resume',
      'CIO resume mistakes',
      'executive resume gaps',
    ],
  },
  {
    slug: 'retained-search-firms',
    title: 'How to Work with Retained Search Firms Without Losing Leverage',
    description: 'Retained search firms work for the client, not the candidate. Understanding how they actually operate changes how you manage every relationship and every search.',
    date: '2026-05-08',
    readTime: '5 min read',
    keywords: [
      'retained search firms CIO',
      'how to work with executive recruiters',
      'executive search firm strategy',
      'CIO headhunter relationship',
      'retained search candidate strategy',
      'executive recruiter tips',
      'how to get on CIO short list',
    ],
  },
  {
    slug: 'target-company-list',
    title: 'How to Build Your Target Company List for an Executive Search',
    description: 'The fastest CIO searches start with a list. Not of job openings. Those are late. A list of forty to sixty companies you would say yes to before the offer is made. Here is how to build it, what to put on it, and what to watch for once you have it.',
    date: '2026-05-10',
    readTime: '6 min read',
    keywords: [
      'executive job search target company list',
      'CIO job search strategy',
      'how to find executive jobs before they post',
      'target company list executive search',
      'CIO search campaign',
      'executive search strategy',
      'technology executive job search',
      'how to build executive job search list',
    ],
  },
  {
    slug: 'cio-vs-cto-which-role',
    title: 'CIO vs CTO: Which Role Is Right for You?',
    description: 'Most technology executives spend their career in one seat without seriously considering whether the other fits better. The CIO drawn to product strategy might be a natural CTO. The CTO frustrated by ambiguity might be a natural CIO. Here is how to tell.',
    date: '2026-05-11',
    readTime: '5 min read',
    keywords: [
      'CIO vs CTO',
      'CIO or CTO which is right for me',
      'difference between CIO and CTO',
      'CIO vs CTO career path',
      'should I be a CIO or CTO',
      'technology executive career decision',
      'CIO CTO difference',
      'chief information officer vs chief technology officer',
    ],
  },
  {
    slug: 'cto-vs-vp-engineering-career-path',
    title: 'CTO vs VP of Engineering: Which Path Is Right for Your Next Move?',
    description: 'Most technology executives reach for the title with more letters. That is the wrong frame. The real question is which role matches how you create value and what kind of work makes you excellent.',
    date: '2026-05-11',
    readTime: '6 min read',
    keywords: [
      'CTO vs VP Engineering',
      'VP engineering vs CTO career path',
      'should I be CTO or VP Engineering',
      'CTO career path',
      'VP of engineering career',
      'technology executive title decision',
      'CTO vs VP engineering difference',
      'chief technology officer vs VP engineering',
    ],
  },
  {
    slug: 'cto-job-search-timeline',
    title: 'How Long Does a CTO Job Search Really Take?',
    description: 'Ask companies how long a CTO search takes and they will say 8 to 12 weeks. Ask candidates and the honest answer is very different. What determines where you fall in the range and what you can actually control.',
    date: '2026-05-11',
    readTime: '5 min read',
    keywords: [
      'how long does CTO job search take',
      'CTO job search timeline',
      'chief technology officer job search time',
      'CTO career transition timeline',
      'how long to find CTO job',
      'technology executive job search timeline',
      'CTO executive search duration',
    ],
  },
  {
    slug: 'linkedin-executive-search-strategy',
    title: 'How to Use LinkedIn in an Active CIO or CTO Search',
    description: 'LinkedIn is the only professional platform where your most important future employers spend time. Used well, it builds inbound interest without looking like you are searching. Used poorly, it is a credibility liability. Here is the difference.',
    date: '2026-05-12',
    readTime: '6 min read',
    keywords: [
      'LinkedIn executive job search',
      'CIO LinkedIn strategy',
      'CTO LinkedIn job search',
      'how to use LinkedIn for executive search',
      'executive LinkedIn profile tips',
      'CIO CTO LinkedIn active search',
      'technology executive LinkedIn strategy',
    ],
  },
  {
    slug: 'how-cios-find-jobs',
    title: 'How Do CIOs Actually Find New Jobs?',
    description: 'Not job boards. Not LinkedIn Easy Apply. Not cold-emailing recruiters. Here is how CIO roles are actually filled and what that means for how to run your search.',
    date: '2026-05-12',
    readTime: '5 min read',
    keywords: [
      'how do CIOs find jobs',
      'CIO job search strategy',
      'how CIOs get hired',
      'CIO hidden job market',
      'how to find CIO job',
      'CIO job search networking',
      'chief information officer job search',
      'how executive CIO jobs are filled',
    ],
  },
  {
    slug: 'target-company-list-cto',
    title: 'How to Build Your Target Company List for a CTO Search',
    description: 'The CTO role has no agreed-upon definition. Before you can build a target company list, you have to decide which version of the CTO you are building toward. That decision shapes every other part of the search.',
    date: '2026-05-10',
    readTime: '7 min read',
    keywords: [
      'CTO job search strategy',
      'how to find CTO jobs',
      'target company list CTO search',
      'chief technology officer job search',
      'CTO executive search',
      'technology executive job search',
      'CTO career transition',
      'how to become CTO',
    ],
  },
  {
    slug: 'executive-search-operating-system',
    title: 'The Search Has No Manager. Here Is How to Build One.',
    description: 'On the day your CIO role ends, you become your own organization: a one-person company with no revenue, no runway, and no manager. Most executives are not prepared for this. Here is what changes when you treat the search like a business.',
    date: '2026-05-10',
    readTime: '7 min read',
    keywords: [
      'executive career transition',
      'CIO job search system',
      'executive search operating system',
      'CIO career transition strategy',
      'technology executive career transition',
      'executive job search structure',
      'how to manage executive job search',
      'executive search campaign strategy',
    ],
  },
  {
    slug: 'executive-coaching-job-search',
    title: "What Executive Coaches Get Wrong About Their Clients' Job Searches",
    description: 'Most executive coaches underestimate how much of the search happens outside the session. Here is what changes when your clients have the right infrastructure.',
    date: '2026-05-10',
    readTime: '6 min read',
    keywords: [
      'executive coaching job search',
      'executive coach career transition',
      'how executive coaches help job search',
      'executive coaching tools',
      'executive job search support',
      'career coaching executives',
      'executive transition coaching',
      'tools for executive coaches',
    ],
  },
]

export function getPost(slug: string): BlogPostMeta | undefined {
  return BLOG_POSTS.find(p => p.slug === slug)
}
