'use client'
import Link from 'next/link'
import { useState, useRef, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'

function renderInline(str: string) {
  return str.split(/\*\*(.+?)\*\*/g).map((chunk, index) => (
    index % 2 === 1 ? <strong key={index}>{chunk}</strong> : <span key={index}>{chunk}</span>
  ))
}

function renderBrief(text: string, isStreaming: boolean) {
  const lines = text.split('\n')
  return lines.map((line, i) => {
    if (line.startsWith('# ')) return null
    if (line.trim() === '---' || line.trim() === '***') return null
    if (line.startsWith('## ')) {
      return (
        <h2 key={i} className="text-[11px] font-bold tracking-[0.1em] uppercase text-slate-400 mt-10 mb-4 first:mt-0 pb-2 border-b border-slate-100">
          {line.slice(3)}
        </h2>
      )
    }
    if (line.startsWith('- ') || line.startsWith('* ')) {
      return (
        <div key={i} className="flex gap-2.5 text-[14px] text-slate-700 leading-relaxed mb-2.5">
          <span className="text-slate-300 shrink-0 select-none mt-0.5">-</span>
          <span>{renderInline(line.slice(2))}</span>
        </div>
      )
    }
    if (line.trim() === '') return <div key={i} className="h-1.5" />
    return (
      <p
        key={i}
        className="text-[14px] text-slate-700 leading-relaxed mb-2.5"
      >
        {renderInline(line)}
      </p>
    )
  }).concat(
    isStreaming ? [
      <span key="cursor" className="inline-block w-0.5 h-4 bg-slate-400 animate-pulse ml-0.5 align-middle" />
    ] : []
  )
}

function secondHeaderIndex(text: string): number {
  let count = 0
  let pos = 0
  while (pos < text.length) {
    const idx = text.indexOf('## ', pos)
    if (idx === -1) break
    count++
    if (count === 2) return idx
    pos = idx + 3
  }
  return -1
}

type DemoContentProps = {
  bypassGate?: boolean
  initialCompany?: string
  initialRole?: string
  autoGenerate?: boolean
}

const ENTRY_HANDOFF: Record<string, string> = {
  landing: 'You came from the landing flow. This demo is the proof-first path before account creation.',
  pricing: 'You came from pricing. Use this brief run to confirm quality before selecting plan intensity.',
  concierge: 'You came from concierge. This self-serve path lets you validate output quality immediately.',
}

type BriefRunPayload = {
  company: string
  role: string
}

export function DemoContent({
  bypassGate: bypassGateProp = false,
  initialCompany = '',
  initialRole = '',
  autoGenerate = false,
}: DemoContentProps) {
  const searchParams = useSearchParams()
  const noGate = bypassGateProp || searchParams.get('full') === '1'
  const source = (searchParams.get('from') ?? '').toLowerCase()

  const [company,  setCompany]  = useState(initialCompany)
  const [role,     setRole]     = useState(initialRole)
  const [content,  setContent]  = useState('')
  const [loading,  setLoading]  = useState(false)
  const [error,    setError]    = useState('')
  const [revealed, setRevealed] = useState(false)
  const [email,    setEmail]    = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [emailError, setEmailError] = useState('')
  const [runStatus, setRunStatus] = useState('')
  const [firstTokenSlow, setFirstTokenSlow] = useState(false)
  const [lastRun, setLastRun] = useState<BriefRunPayload | null>(null)
  const briefRef = useRef<HTMLDivElement>(null)
  const autoGeneratedRef = useRef(false)

  const gateIdx   = secondHeaderIndex(content)
  const gateReady = gateIdx !== -1
  const gated     = gateReady && !revealed && !noGate

  const visibleContent = gated ? content.slice(0, gateIdx).trimEnd() : content

  async function generateBrief(targetCompany: string, targetRole: string) {
    const trimmedCompany = targetCompany.trim()
    const trimmedRole = targetRole.trim()
    if (!trimmedCompany || !trimmedRole) return
    if (loading) {
      setRunStatus('Already generating. Please wait for this run to finish.')
      return
    }

    setLastRun({ company: trimmedCompany, role: trimmedRole })
    setContent('')
    setError('')
    setRevealed(false)
    setLoading(true)
    setRunStatus('Run started. Building brief...')
    setFirstTokenSlow(false)

    const firstTokenTimer = setTimeout(() => {
      setFirstTokenSlow(true)
      setRunStatus('Still working. Warming up the model...')
    }, 3000)

    try {
      const res = await fetch('/api/demo-brief', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ company: trimmedCompany, role: trimmedRole }),
      })

      if (!res.ok || !res.body) {
        const details = (await res.text().catch(() => '')).trim()
        if (res.status === 429) {
          const retryAfter = res.headers.get('Retry-After')
          setError(retryAfter ? `Rate limit reached. Retry in ${retryAfter}s.` : 'Rate limit reached. Please retry in a moment.')
        } else {
          setError(details || 'Something went wrong. Please try again.')
        }
        setRunStatus('')
        return
      }

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let full = ''
      let gotFirstChunk = false

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        if (!gotFirstChunk) {
          gotFirstChunk = true
          setFirstTokenSlow(false)
          setRunStatus('Streaming response...')
          clearTimeout(firstTokenTimer)
        }
        full += decoder.decode(value, { stream: true })
        setContent(full)
      }

      if (full.startsWith('__ERROR__')) {
        setError('Something went wrong. Please try again.')
        setContent('')
        setRunStatus('')
      } else if (!full.trim()) {
        setError('No response returned. Please retry.')
        setRunStatus('')
      } else {
        setRunStatus('')
      }
    } catch {
      setError('Something went wrong. Please try again.')
      setRunStatus('')
    } finally {
      clearTimeout(firstTokenTimer)
      setLoading(false)
      setFirstTokenSlow(false)
    }
  }

  useEffect(() => {
    if (!autoGenerate) return
    if (autoGeneratedRef.current) return
    if (!initialCompany.trim() || !initialRole.trim()) return
    autoGeneratedRef.current = true
    void generateBrief(initialCompany, initialRole)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, initialCompany, initialRole])

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault()
    await generateBrief(company, role)
  }

  async function handleRetryLastRun() {
    if (!lastRun || loading) return
    await generateBrief(lastRun.company, lastRun.role)
  }

  async function handleEmailSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!email.trim() || submitting) return
    setEmailError('')
    setSubmitting(true)
    try {
      const res = await fetch('/api/demo-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: email.trim(), company: company.trim(), role: role.trim() }),
      })
      const data = await res.json()
      if (!res.ok || !data.ok) {
        setEmailError('Please enter a valid email address.')
        return
      }
      setRevealed(true)
    } catch {
      setEmailError('Something went wrong. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  const inputCls = 'w-full border border-slate-200 rounded px-3 py-2.5 text-[14px] text-slate-900 placeholder:text-slate-300 focus:outline-none focus:border-slate-500'
  const labelCls = 'block text-[11px] font-bold tracking-[0.07em] uppercase text-slate-400 mb-1.5'

  return (
    <div className="min-h-screen bg-white font-sans">

      <nav className="bg-slate-900 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link href="/" className="text-[10px] font-bold tracking-[0.18em] uppercase">
            <span className="text-white">Starting </span><span className="text-orange-500">Monday</span>
          </Link>
          <div className="flex items-center gap-5">
            <Link href="/login" className="text-[13px] text-slate-400 hover:text-white transition-colors">
              Log in
            </Link>
            <Link
              href="/signup?from=demo"
              className="text-[13px] font-semibold text-white bg-orange-500 px-4 py-1.5 rounded hover:bg-orange-600 transition-colors"
            >
              Create account
            </Link>
          </div>
        </div>
      </nav>

      <main className="max-w-2xl mx-auto px-4 sm:px-6 py-10 sm:py-14">
{/* Header */}
        <div className="mb-8">
          <h2 className="text-[10px] font-bold tracking-[0.14em] uppercase text-orange-500 mb-2">Live demo</h2>
          <h1 className="text-[26px] font-bold text-slate-900 leading-tight mb-2">
            Improve the conversation before it starts.
          </h1>
          <p className="text-[14px] text-slate-500 leading-relaxed">
            Enter any company and role. See the same prep brief users run before high-stakes conversations.
          </p>
          <p className="text-[12px] text-slate-500 leading-relaxed mt-2">Trust and confidentiality: demo requests are used only to generate this brief and are not sold or shared.</p>
          {source && ENTRY_HANDOFF[source] && (
            <p className="text-[12px] text-slate-500 leading-relaxed mt-1">{ENTRY_HANDOFF[source]}</p>
          )}
          <p className="text-[12px] text-slate-500 leading-relaxed mt-1">Pilot snapshot: 81% reached first interview in 30 days (n=27).</p>
        </div>

        <section id="demo-context" className="border border-slate-200 rounded-lg p-5 sm:p-6 mb-8 bg-slate-50">
          <h2 className="text-[11px] font-bold tracking-[0.1em] uppercase text-slate-500 mb-3">Before you run the demo</h2>
          <div className="space-y-4">
            <div>
              <p className="text-[13px] font-semibold text-slate-900 mb-1">Why this company context matters</p>
              <p className="text-[13px] text-slate-600 leading-relaxed">
                Senior searches are won on context quality, not volume. This brief gives you a point of view, likely objections, and peer-level questions.
              </p>
            </div>
            <div>
              <p className="text-[13px] font-semibold text-slate-900 mb-1">Typical week of signals</p>
              <ul className="space-y-1.5 text-[13px] text-slate-600 leading-relaxed">
                <li>- Monday: leadership or org-change disclosures</li>
                <li>- Wednesday: role-shaping movement and language updates</li>
                <li>- Friday: relationship follow-through priorities</li>
              </ul>
            </div>
          </div>
          <p className="text-[12px] text-slate-500 mt-4">
            Pilot snapshot (Jan-May 2026): 81% reached first interview in 30 days, denominator 27 executives.{' '}
            <Link href="/references" className="underline underline-offset-2 hover:text-slate-800 transition-colors">
              Evidence and references
            </Link>
            .
          </p>
        </section>

        {/* Input form */}
        <section id="run-demo" className="mb-8">
          <h2 className="text-[18px] font-bold text-slate-900 mb-3">Run the demo</h2>
          <form onSubmit={handleGenerate} className="bg-white border border-slate-200 rounded p-6 flex flex-col gap-4">
            <div>
              <label className={labelCls}>Company <span className="text-red-500">*</span></label>
              <input
                type="text"
                value={company}
                onChange={e => setCompany(e.target.value)}
                placeholder="Salesforce"
                required
                disabled={loading}
                className={inputCls}
              />
            </div>
            <div>
              <label className={labelCls}>Role <span className="text-red-500">*</span></label>
              <input
                type="text"
                value={role}
                onChange={e => setRole(e.target.value)}
                placeholder="Chief Information Officer"
                required
                disabled={loading}
                className={inputCls}
              />
            </div>
            <button
              type="submit"
              disabled={!company.trim() || !role.trim() || loading}
              className="bg-orange-500 hover:bg-orange-600 disabled:opacity-30 text-white text-[13px] font-semibold px-6 py-2.5 rounded transition-colors cursor-pointer border-0 disabled:cursor-not-allowed self-start"
            >
              {loading ? 'Generating...' : content ? 'Regenerate' : 'Generate brief'}
            </button>
            {runStatus && <p className="text-[12px] text-slate-500">{runStatus}</p>}
            {firstTokenSlow && <p className="text-[12px] text-slate-500">First response chunk is taking longer than usual.</p>}
            {lastRun && !loading && (
              <button
                type="button"
                onClick={handleRetryLastRun}
                className="text-[12px] text-slate-600 underline underline-offset-2 hover:text-slate-900 self-start"
              >
                Retry last run
              </button>
            )}
            {error && <p className="text-[13px] text-red-600">{error}</p>}
          </form>
        </section>

        {/* Brief */}
        {(content || loading) && (
          <section id="brief-output" className="relative" ref={briefRef}>
            <h2 className="text-[18px] font-bold text-slate-900 mb-3">Brief output</h2>
            {/* Visible content */}
            <div className="bg-white border border-slate-200 rounded p-6 sm:p-8">
              {renderBrief(visibleContent, loading)}
              {loading && !content && (
                <div className="flex items-center gap-2 py-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-300 animate-pulse inline-block" />
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-300 animate-pulse inline-block [animation-delay:150ms]" />
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-300 animate-pulse inline-block [animation-delay:300ms]" />
                </div>
              )}
            </div>

            {/* Email gate */}
            {gated && (
              <div className="mt-0">
                {/* Fade */}
                <div className="h-16 bg-gradient-to-b from-transparent to-slate-50 -mt-16 relative z-10 pointer-events-none" />

                {/* Gate panel */}
                <div className="bg-slate-50 border border-slate-200 border-t-0 rounded-b px-6 sm:px-8 py-8">
                  <p className="text-[15px] font-semibold text-slate-900 mb-1.5">
                    The brief continues.
                  </p>
                  <p className="text-[13px] text-slate-500 mb-6 leading-relaxed">
                    Unlock the rest: likely questions, objections to handle early, and trust-building points for decision makers.
                  </p>
                  <form onSubmit={handleEmailSubmit} className="flex flex-col sm:flex-row gap-3 max-w-md">
                    <input
                      type="email"
                      value={email}
                      onChange={e => setEmail(e.target.value)}
                      placeholder="you@company.com"
                      required
                      className="flex-1 border border-slate-200 rounded px-3 py-2.5 text-[14px] text-slate-900 placeholder:text-slate-300 focus:outline-none focus:border-slate-500"
                    />
                    <button
                      type="submit"
                      disabled={!email.trim() || submitting}
                      className="bg-slate-900 hover:bg-slate-700 disabled:opacity-30 text-white text-[13px] font-semibold px-5 py-2.5 rounded transition-colors cursor-pointer border-0 disabled:cursor-not-allowed shrink-0"
                    >
                      {submitting ? 'One moment...' : 'Unlock full brief'}
                    </button>
                  </form>
                  {emailError && <p className="mt-2 text-[12px] text-red-600">{emailError}</p>}
                  <p className="mt-3 text-[11px] text-slate-400">No credit card required.</p>
                </div>
              </div>
            )}

          </section>
        )}

        {/* Pre-generation context */}
        {!content && !loading && (
          <section id="full-account" className="border-t border-slate-100 pt-8">
            <h2 className="text-[18px] font-bold text-slate-900 mb-3">What you get with a full account</h2>
            <p className="text-[11px] font-bold tracking-[0.1em] uppercase text-slate-400 mb-5">Included capabilities</p>
            <div className="flex flex-col gap-3">
                {[
                'Auto-generated prep brief for each target company',
                'Signal intelligence with alerts before roles are broadly posted',
                'Daily priorities that reduce reactive moves',
              ].map((item, i) => (
                <div key={i} className="flex gap-3 items-start">
                  <span className="text-orange-500 font-bold text-[11px] shrink-0 mt-0.5">{i + 1}</span>
                  <p className="text-[13px] text-slate-500 leading-relaxed">{item}</p>
                </div>
              ))}
            </div>
            <div className="mt-8 flex flex-col sm:flex-row gap-3 items-start">
              <Link
                href="/signup"
                className="inline-block bg-orange-500 text-white text-[13px] font-semibold px-6 py-2.5 rounded hover:bg-orange-600 transition-colors"
              >
                Create account
              </Link>
              <p className="text-[12px] text-slate-400 sm:mt-2.5">30 days free. No credit card.</p>
            </div>
          </section>
        )}

      </main>
    </div>
  )
}

export default function DemoPage() {
  return (
    <Suspense fallback={null}>
      <DemoContent />
    </Suspense>
  )
}
