export const experienceAgents = [
  {
    id: 'route-inventory-agent.yml',
    name: 'Route Inventory Agent',
    status: 'Done',
    maxAgeMinutes: 60 * 30,
    recommendation: 'Regenerate inventory and reconcile newly added or removed routes before claiming full-site compliance.',
  },
  {
    id: 'experience-vitals-agent.yml',
    name: 'Experience Vitals Agent',
    status: 'In Progress',
    maxAgeMinutes: 60 * 8,
    sesWired: true,
    recommendation: 'Triage tier-level vitals budget breaches (now sourced from SES) and reconcile baseline drift before regressions harden.',
  },
  {
    id: 'cognitive-load-agent.yml',
    name: 'Cognitive Load Agent',
    status: 'In Progress',
    maxAgeMinutes: 60 * 24 * 8,
    recommendation: 'Review high-density public routes and reduce CTA competition or paragraph density before fluency regresses further.',
  },
  {
    id: 'cognitive-fluency-calibration-dispatch.yml',
    name: 'Cognitive Fluency Calibration Dispatch',
    status: 'In Progress',
    maxAgeMinutes: 60 * 24 * 40,
    recommendation: 'Run Page Experience Auditor on the monthly worst routes packet and feed the resulting corrections back into deterministic scoring.',
  },
  {
    id: 'trust-integrity-agent.yml',
    name: 'Trust Integrity Agent',
    status: 'Done',
    maxAgeMinutes: 60 * 24,
    recommendation: 'Monitor dashboard signal parity contracts and relative-time staleness violations; escalate P0 count mismatches immediately.',
  },
  {
    id: 'visual-sentinel-agent.yml',
    name: 'Visual Sentinel Agent',
    status: 'In Progress',
    maxAgeMinutes: 60 * 12,
    sesWired: false,
    recommendation: 'Add rendered screenshot/diff checks; typography and accent telemetry are now tracked source-side via luxury-page-sentinel-rubric.json.',
  },
  {
    id: 'journey-synthetic-agent.yml',
    name: 'Journey Synthetic Agent',
    status: 'In Progress',
    maxAgeMinutes: 60 * 6,
    sesWired: false,
    recommendation: 'Normalize journey step percentiles and abandonment-risk scoring into portfolio rollup issue clustering.',
  },
]
