[build]
builder = "nixpacks"
buildCommand = "echo 'no build step'"

[deploy]
startCommand = "NODE_OPTIONS=--max-old-space-size=1536 node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
