-- outreach draft stored on each signal (generated by Claude, ready to copy-send)
ALTER TABLE company_signals ADD COLUMN IF NOT EXISTS outreach_draft jsonb;

-- per-company role targeting: what the executive specifically wants at this company
ALTER TABLE companies ADD COLUMN IF NOT EXISTS role_watch_description text;
